# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 05 Jul 2013 15:25:15 +0000
*               @ALL          1
*               @user         8
