<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: napalm
 * Date: Mon, 05 Aug 2013 03:06:01 +0000
 */

$conf['title'] = 'Mental Minis';
$conf['license'] = 'gnufdl';
$conf['baseurl'] = 'https://mentalminis.com';
$conf['dmode'] = 0775;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['gzip_output'] = 1;
$conf['proxy']['pass'] = '<b>cDF0YmlrZXM=';
$conf['plugin']['gallery']['cols'] = 3;
$conf['plugin']['gallery']['sort'] = 'date';
$conf['plugin']['gallery']['options'] = 'cache,lightbox';

// end auto-generated content
